apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: staging
images:
- name: kowlon/go-echo
  newName: 723948246008.dkr.ecr.ap-southeast-1.amazonaws.com/go-ci-cd
  newTag: stg-v.0.0.4
